### ISSUE TITLE
Problem with matplotlib NavigationToolbar2QTAgg

### ISSUE THREAD

**Issue by PedroVenancio** [msweier/ProfileFromPoints#1]
Hi, 

After today's or yesterday's update of matplotlib to 2.0.0-1 on OSGeo4W (64bits), statist stoped work on QGIS 2.18.5:

Python error: Couldn't load plugin ProfileFromPoints due to an error when calling its classFactory() method See message log (Python Error) for more details.

Couldn't load plugin ProfileFromPoints due to an error when calling its classFactory() method 

ImportError: cannot import name NavigationToolbar2QTAgg 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/pedro/.qgis2/python/plugins\ProfileFromPoints\__init__.py", line 34, in classFactory
    from .profileFromPoints import ProfileFromPoints
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/pedro/.qgis2/python/plugins\ProfileFromPoints\profileFromPoints.py", line 28, in 
    from profileFromPoints_dialog import ProfileFromPointsDialog
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/pedro/.qgis2/python/plugins\ProfileFromPoints\profileFromPoints_dialog.py", line 39, in 
    from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg as NavigationToolbar
ImportError: cannot import name NavigationToolbar2QTAgg

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.5 Las Palmas, f85ff26

**Comment by BishopGIS** [comment]
In new version of matplotlib you should import `NavigationToolbar2QT` instead  'NavigationToolbar2QTAgg'
